### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by daglem** [povik/yosys-slang#1]
May I suggest that you open for "Discussions" in the repository settings?

This would make for a more natural place to discuss issues as your project moves along, and you could possibly ask @MikePopoloski to chime in there as his excellent [slang](https://github.com/MikePopoloski/slang) gets some real battle testing :rocket: 

Good luck with the project, I think this has the potential to make a world of difference for open source synthesis of SystemVerilog :+1:

**Comment by povik** [comment]
Sure, done!
