### ISSUE TITLE
Yosys API change breaks `.bits`

### ISSUE THREAD

**Issue by akashlevy** [povik/yosys-slang#63]
In the latest version of Yosys `.bits` was changed to `.bits()`. This should eventually be reflected in the slang frontend.

**Comment by akashlevy** [comment]
Can make a quick PR for this if needed

**Comment by povik** [comment]
Thanks. I will see if there's a good way to write it in a way which will work both before and after the YosysHQ/yosys#4516 change

**Comment by povik** [comment]
Presumably fixed in [7a9960c](https://github.com/povik/yosys-slang/commit/7a9960c2ea34cba66b9d3941f12038eaa464f46f) (in the staging branch)
